name: Patch and Build

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches
      - name: Build NogyangSpigot Jar(Main Jar)
        run: ./gradlew createreobfpaperclipjar
      - name: Get Release Number
        if: startsWith(github.ref_name, 'ver/')
        run: echo "RELEASE=$(git ls-remote --tags origin | grep "build/${{ env.MC_VERSION }}" | wc -l)" >> $GITHUB_ENV
      - name: Release Artifacts
        if: startsWith(github.ref_name, 'ver/')
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: "Build #${{ env.RELEASE }} for ${{ env.MC_VERSION }}"
          tag_name: build/${{ env.MC_VERSION }}/${{ env.RELEASE }}
          target_commitish: ${{ github.ref_name }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: build/libs/*.jar
      - name: Release Artifacts (Latest/Stable)
        if: startsWith(github.ref_name, 'ver/')
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: "Build #${{ env.RELEASE }} for ${{ env.MC_VERSION }}"
          tag_name: build/${{ env.MC_VERSION }}/latest
          target_commitish: ${{ github.ref_name }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: build/libs/*.jar
      - name: Release Artifacts (Latest/Development)
        if: startsWith(github.ref_name, 'dev/')
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: "Development Build for ${{ env.MC_VERSION }}"
          tag_name: build/${{ env.MC_VERSION }}/latest
          target_commitish: ${{ github.ref_name }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: build/libs/*.jar
